version: '3.1'

services:
  frontend:
    build : frontend    
    image: frontend
    ports:
      - 4000:3000
    depends_on:
      - backend
  backend:
    build: backend      
    image: backend
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest 
  my_super_app:
    build: ./my_super_app
    image: "my_super_app:latest"
    container_name: my_supper_app
    depends_on:
      - mongodb
    command: sh -c "/wait && /sayhello"
    environment:
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
